import {
  BLIZZARD,
  BLOWING_DUST,
  BLOWING_SAND,
  BLOWING_SNOW,
  BLOWING_SPRAY,
  LIGHT_DRIZZLE,
  DRIZZLE,
  HEAVY_DRIZZLE,
  FOG,
  LIGHT_FREEZING_DRIZZLE,
  FREEZING_DRIZZLE,
  HEAVY_FREEZING_DRIZZLE,
  FREEZING_RAIN,
  FREEZING_SPRAY,
  HAZE,
  HEAVY_FREEZING_RAIN,
  HEAVY_ICE_PELLETS_SHOWERS,
  HEAVY_ICE_PELLETS,
  HEAVY_RAIN_SHOWERS,
  HEAVY_RAIN,
  HEAVY_SLEET,
  HEAVY_SNOW_SHOWERS,
  HEAVY_SNOW,
  ICE_FOG,
  ICE_PELLETS_SHOWERS,
  ICE_PELLETS,
  LIGHT_FREEZING_RAIN,
  LIGHT_ICE_PELLETS_SHOWERS,
  LIGHT_ICE_PELLETS,
  LIGHT_RAIN_SHOWERS,
  LIGHT_RAIN,
  LIGHT_SLEET,
  LIGHT_SNOW_SHOWERS,
  LIGHT_SNOW,
  MIST,
  MOSTLY_CLOUDY,
  MOSTLY_SUNNY,
  OVERCAST,
  PARTLY_CLOUDY,
  RAIN_SHOWERS,
  RAIN,
  SLEET,
  SMOKE,
  SNOW,
  SQUALL,
  SUNNY,
  THUNDERSTORM,
  VOLCANIC_ASH,
  WATERSPOUT,
} from 'common/constants';

export const ICONS_NAMES_MAP = {
  [BLIZZARD]: 'blizzard',
  [BLOWING_DUST]: 'blowing-dust',
  [BLOWING_SAND]: 'blowing-sand',
  [BLOWING_SNOW]: 'blowing-snow',
  [BLOWING_SPRAY]: 'blowing-spray',
  [LIGHT_DRIZZLE]: 'drizzle',
  [DRIZZLE]: 'drizzle',
  [HEAVY_DRIZZLE]: 'drizzle',
  [FOG]: 'fog',
  [LIGHT_FREEZING_DRIZZLE]: 'freezing-drizzle',
  [FREEZING_DRIZZLE]: 'freezing-drizzle',
  [HEAVY_FREEZING_DRIZZLE]: 'freezing-drizzle',
  [FREEZING_RAIN]: 'freezing-rain',
  [FREEZING_SPRAY]: 'freezing-spray',
  [HAZE]: 'haze',
  [HEAVY_FREEZING_RAIN]: 'heavy-freezing-rain',
  [HEAVY_ICE_PELLETS_SHOWERS]: 'heavy-ice-pellets-showers',
  [HEAVY_ICE_PELLETS]: 'heavy-ice-pellets',
  [HEAVY_RAIN_SHOWERS]: 'heavy-rain-showers',
  [HEAVY_RAIN]: 'heavy-rain',
  [HEAVY_SLEET]: 'heavy-sleet',
  [HEAVY_SNOW_SHOWERS]: 'heavy-snow-showers',
  [HEAVY_SNOW]: 'heavy-snow',
  [ICE_FOG]: 'ice-fog',
  [ICE_PELLETS_SHOWERS]: 'ice-pellets-showers',
  [ICE_PELLETS]: 'ice-pellets',
  [LIGHT_FREEZING_RAIN]: 'light-freezing-rain',
  [LIGHT_ICE_PELLETS_SHOWERS]: 'light-ice-pellets-showers',
  [LIGHT_ICE_PELLETS]: 'light-ice-pellets',
  [LIGHT_RAIN_SHOWERS]: 'light-rain-showers',
  [LIGHT_RAIN]: 'light-rain',
  [LIGHT_SLEET]: 'light-sleet',
  [LIGHT_SNOW_SHOWERS]: 'light-snow-showers',
  [LIGHT_SNOW]: 'light-snow',
  [MIST]: 'mist',
  [MOSTLY_CLOUDY]: 'mostly-cloudy',
  [MOSTLY_SUNNY]: 'mostly-sunny',
  [OVERCAST]: 'overcast',
  [PARTLY_CLOUDY]: 'partly-cloudy',
  [RAIN_SHOWERS]: 'rain-showers',
  [RAIN]: 'rain',
  [SLEET]: 'sleet',
  [SMOKE]: 'smoke',
  [SNOW]: 'snow',
  [SQUALL]: 'squall',
  [SUNNY]: 'sunny',
  [THUNDERSTORM]: 'thunderstorm',
  [VOLCANIC_ASH]: 'volcanic-ash',
  [WATERSPOUT]: 'waterspout',
};

export default ICONS_NAMES_MAP;
