#                                               #
#                                               #
# docker-compose.yml FILE FOR LOCAL DEVELOPMENT #
#                                               #
#                                               #

version: '3'

services:
  clime:
    image: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$CI_COMMIT_SHA

  nginx:
    build: nginx
    links:
      - memcached:memcached1
    depends_on:
      - php

  tester:
    image: registry.git.herewetest.com/apalon-web/weather-live-backend-automation/tester
    links:
      - nginx:x.x
      - nginx:api.x.x
    profiles:
      - do_not_start_automatically
