import {
  BLIZZARD,
  BLOWING_DUST,
  BLOWING_SAND,
  BLOWING_SNOW,
  BLOWING_SPRAY,
  LIGHT_DRIZZLE,
  DRIZZLE,
  HEAVY_DRIZZLE,
  FOG,
  LIGHT_FREEZING_DRIZZLE,
  FREEZING_DRIZZLE,
  HEAVY_FREEZING_DRIZZLE,
  FREEZING_RAIN,
  FREEZING_SPRAY,
  HAZE,
  HEAVY_FREEZING_RAIN,
  HEAVY_ICE_PELLETS_SHOWERS,
  HEAVY_ICE_PELLETS,
  HEAVY_RAIN_SHOWERS,
  HEAVY_RAIN,
  HEAVY_SLEET,
  HEAVY_SNOW_SHOWERS,
  HEAVY_SNOW,
  ICE_FOG,
  ICE_PELLETS_SHOWERS,
  ICE_PELLETS,
  LIGHT_FREEZING_RAIN,
  LIGHT_ICE_PELLETS_SHOWERS,
  LIGHT_ICE_PELLETS,
  LIGHT_RAIN_SHOWERS,
  LIGHT_RAIN,
  LIGHT_SLEET,
  LIGHT_SNOW_SHOWERS,
  LIGHT_SNOW,
  MIST,
  MOSTLY_CLOUDY,
  MOSTLY_SUNNY,
  OVERCAST,
  PARTLY_CLOUDY,
  RAIN_SHOWERS,
  RAIN,
  SLEET,
  SMOKE,
  SNOW,
  SQUALL,
  SUNNY,
  THUNDERSTORM,
  VOLCANIC_ASH,
  WATERSPOUT,
} from 'common/constants';

export type WeatherStateId =
  | typeof BLIZZARD
  | typeof BLOWING_DUST
  | typeof BLOWING_SAND
  | typeof BLOWING_SNOW
  | typeof BLOWING_SPRAY
  | typeof LIGHT_DRIZZLE
  | typeof DRIZZLE
  | typeof HEAVY_DRIZZLE
  | typeof FOG
  | typeof LIGHT_FREEZING_DRIZZLE
  | typeof FREEZING_DRIZZLE
  | typeof HEAVY_FREEZING_DRIZZLE
  | typeof FREEZING_RAIN
  | typeof FREEZING_SPRAY
  | typeof HAZE
  | typeof HEAVY_FREEZING_RAIN
  | typeof HEAVY_ICE_PELLETS_SHOWERS
  | typeof HEAVY_ICE_PELLETS
  | typeof HEAVY_RAIN_SHOWERS
  | typeof HEAVY_RAIN
  | typeof HEAVY_SLEET
  | typeof HEAVY_SNOW_SHOWERS
  | typeof HEAVY_SNOW
  | typeof ICE_FOG
  | typeof ICE_PELLETS_SHOWERS
  | typeof ICE_PELLETS
  | typeof LIGHT_FREEZING_RAIN
  | typeof LIGHT_ICE_PELLETS_SHOWERS
  | typeof LIGHT_ICE_PELLETS
  | typeof LIGHT_RAIN_SHOWERS
  | typeof LIGHT_RAIN
  | typeof LIGHT_SLEET
  | typeof LIGHT_SNOW_SHOWERS
  | typeof LIGHT_SNOW
  | typeof MIST
  | typeof MOSTLY_CLOUDY
  | typeof MOSTLY_SUNNY
  | typeof OVERCAST
  | typeof PARTLY_CLOUDY
  | typeof RAIN_SHOWERS
  | typeof RAIN
  | typeof SLEET
  | typeof SMOKE
  | typeof SNOW
  | typeof SQUALL
  | typeof SUNNY
  | typeof THUNDERSTORM
  | typeof VOLCANIC_ASH
  | typeof WATERSPOUT;

export default WeatherStateId;
