export const DEFAULT_BLUR_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO0aX5RDwAE0gIoYaK/HgAAAABJRU5ErkJggg==';

export default DEFAULT_BLUR_DATA_URL;
