export const CLIME_LOCAL_STORAGE_PREFIX = 'clm.';

export const TEMPERATURE_UNIT = `${CLIME_LOCAL_STORAGE_PREFIX}tu`;
export const WIND_SPEED_UNIT = `${CLIME_LOCAL_STORAGE_PREFIX}wsu`;
export const PRECIPITATION_UNIT = `${CLIME_LOCAL_STORAGE_PREFIX}pru`;
export const PRESSURE_UNIT = `${CLIME_LOCAL_STORAGE_PREFIX}pu`;
export const DISTANCE_UNIT = `${CLIME_LOCAL_STORAGE_PREFIX}du`;
export const TIME_FORMAT = `${CLIME_LOCAL_STORAGE_PREFIX}tf`;
export const LAST_TIME_POPUP_OPENED = `${CLIME_LOCAL_STORAGE_PREFIX}ltpo`;
